// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoasterBuddy.Models;

#nullable disable

namespace RoasterBuddy.Migrations
{
    [DbContext(typeof(RoasterBuddyContext))]
    [Migration("20230727015009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("RoasterBuddy.Models.Client", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ID = new Guid("f8c6521e-8aab-4927-86ba-fdbc0bb0d0eb"),
                            Address = "123 Main St, Louisville, KY",
                            ContactInformation = "bluegrassbeans@example.com",
                            Name = "Bluegrass Beans"
                        },
                        new
                        {
                            ID = new Guid("acdda976-63ad-47fa-b7d6-d89ea9ecbfe5"),
                            Address = "456 River Rd, Louisville, KY",
                            ContactInformation = "rivercityroasts@example.com",
                            Name = "River City Roasts"
                        },
                        new
                        {
                            ID = new Guid("4e21b65e-202b-4e56-9184-86c1c8f61410"),
                            Address = "789 Derby Ln, Louisville, KY",
                            ContactInformation = "derbydaycoffee@example.com",
                            Name = "Derby Day Coffee"
                        },
                        new
                        {
                            ID = new Guid("a3480537-8058-4499-a0aa-7717b261f826"),
                            Address = "321 Bardstown Rd, Louisville, KY",
                            ContactInformation = "bardstownbrews@example.com",
                            Name = "Bardstown Brews"
                        },
                        new
                        {
                            ID = new Guid("1a4be23b-e81d-499a-ae49-129b61b2d12c"),
                            Address = "654 Southern Pkwy, Louisville, KY",
                            ContactInformation = "southerncomfortcafe@example.com",
                            Name = "Southern Comfort Cafe"
                        },
                        new
                        {
                            ID = new Guid("ed8ba7b1-58c5-48ec-8843-e02b226347ad"),
                            Address = "987 Cherokee Rd, Louisville, KY",
                            ContactInformation = "cherokeeparkperks@example.com",
                            Name = "Cherokee Park Perks"
                        },
                        new
                        {
                            ID = new Guid("4aff52d3-7077-4ca4-b070-8f3f45ee98b5"),
                            Address = "135 Churchill Dr, Louisville, KY",
                            ContactInformation = "churchillgrinds@example.com",
                            Name = "Churchill Grinds"
                        },
                        new
                        {
                            ID = new Guid("aad6251c-be37-48aa-9d22-67b2ad183c2b"),
                            Address = "246 East Market St, Louisville, KY",
                            ContactInformation = "nulujava@example.com",
                            Name = "NuLu Java"
                        });
                });

            modelBuilder.Entity("RoasterBuddy.Models.Order", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOrdered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoastLevel")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ClientId");

                    b.HasIndex("SourceId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ID = new Guid("98f7cb52-0b0f-4b5e-8594-a20adb9a6da9"),
                            Amount = 10,
                            ClientId = new Guid("f8c6521e-8aab-4927-86ba-fdbc0bb0d0eb"),
                            DateOrdered = new DateTime(2023, 7, 26, 21, 50, 9, 47, DateTimeKind.Local).AddTicks(1351),
                            Name = "Bluegrass Beans",
                            Price = 120.00m,
                            RoastLevel = 0,
                            SourceId = new Guid("1a4d58e2-ba0b-4153-af81-fd0b6049e348")
                        },
                        new
                        {
                            ID = new Guid("fd996062-bd49-4bd8-9bca-297bbcc21cff"),
                            Amount = 8,
                            ClientId = new Guid("acdda976-63ad-47fa-b7d6-d89ea9ecbfe5"),
                            DateOrdered = new DateTime(2023, 7, 26, 21, 50, 9, 47, DateTimeKind.Local).AddTicks(1427),
                            Name = "River City Roasts",
                            Price = 110.00m,
                            RoastLevel = 1,
                            SourceId = new Guid("ff85d5a3-945b-4a97-9d61-d808f3893e5f")
                        });
                });

            modelBuilder.Entity("RoasterBuddy.Models.Source", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Farm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Sources");

                    b.HasData(
                        new
                        {
                            ID = new Guid("1a4d58e2-ba0b-4153-af81-fd0b6049e348"),
                            Cost = 2.40m,
                            Farm = "Fazenda Santa Ines, Minas Gerais",
                            Location = "Brazil"
                        },
                        new
                        {
                            ID = new Guid("ff85d5a3-945b-4a97-9d61-d808f3893e5f"),
                            Cost = 2.75m,
                            Farm = "Carmo Estate, Sul de Minas",
                            Location = "Brazil"
                        },
                        new
                        {
                            ID = new Guid("07b4d790-a98e-480a-85c2-0f03882c6be9"),
                            Cost = 4.67m,
                            Farm = "La Soledad, Acatenango",
                            Location = "Guatemala"
                        },
                        new
                        {
                            ID = new Guid("611ce66e-f50c-48d8-9ad6-e6233f76d1b2"),
                            Cost = 2.67m,
                            Farm = "Finca El Injerto, Huehuetenango",
                            Location = "Guatemala"
                        },
                        new
                        {
                            ID = new Guid("282b9b7e-21f7-43c7-a275-10ddb989970f"),
                            Cost = 4.00m,
                            Farm = "Hacienda La Esmeralda, Boquete",
                            Location = "Panama"
                        },
                        new
                        {
                            ID = new Guid("bebaae8a-9742-415a-9619-0d3f3d1e0710"),
                            Cost = 3.00m,
                            Farm = "Finca Deborah, Volcan",
                            Location = "Panama"
                        },
                        new
                        {
                            ID = new Guid("9d9b6bd1-8724-4599-997b-29851e27370e"),
                            Cost = 3.00m,
                            Farm = "Hacienda El Roble, Santander",
                            Location = "Colombia"
                        },
                        new
                        {
                            ID = new Guid("395c5405-206b-441e-9c04-3dc67f285481"),
                            Cost = 2.91m,
                            Farm = "Finca Los Nogales, Tolima",
                            Location = "Colombia"
                        },
                        new
                        {
                            ID = new Guid("e025b756-c544-4101-99e9-4d1e396c4674"),
                            Cost = 3.78m,
                            Farm = "Hunkute Cooperative, Sidamo",
                            Location = "Ethiopia"
                        },
                        new
                        {
                            ID = new Guid("d1a363a7-f81f-4bec-ad3b-6dbd565904ce"),
                            Cost = 4.29m,
                            Farm = "Guji Highland Farm, Guji",
                            Location = "Ethiopia"
                        });
                });

            modelBuilder.Entity("RoasterBuddy.Models.Order", b =>
                {
                    b.HasOne("RoasterBuddy.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId");

                    b.HasOne("RoasterBuddy.Models.Source", "Source")
                        .WithMany("Orders")
                        .HasForeignKey("SourceId");

                    b.Navigation("Client");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("RoasterBuddy.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RoasterBuddy.Models.Source", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
