// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoasterBuddy.Models;

#nullable disable

namespace RoasterBuddy.Migrations
{
    [DbContext(typeof(RoasterBuddyContext))]
    [Migration("20230725205305_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("RoasterBuddy.Models.Client", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactInformation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ID = new Guid("f44f57d2-9167-4810-ac47-aedbaf8d5cbc"),
                            Address = "123 Main St, Louisville, KY",
                            ContactInformation = "bluegrassbeans@example.com",
                            Name = "Bluegrass Beans"
                        },
                        new
                        {
                            ID = new Guid("8d01c2a1-2e77-4ba0-a0bb-7f5826f4c781"),
                            Address = "456 River Rd, Louisville, KY",
                            ContactInformation = "rivercityroasts@example.com",
                            Name = "River City Roasts"
                        },
                        new
                        {
                            ID = new Guid("3f5fbbec-a13c-4c64-8c45-daf9819a67ba"),
                            Address = "789 Derby Ln, Louisville, KY",
                            ContactInformation = "derbydaycoffee@example.com",
                            Name = "Derby Day Coffee"
                        },
                        new
                        {
                            ID = new Guid("4ccace88-d885-4e44-8c87-f9a153f4c77f"),
                            Address = "321 Bardstown Rd, Louisville, KY",
                            ContactInformation = "bardstownbrews@example.com",
                            Name = "Bardstown Brews"
                        },
                        new
                        {
                            ID = new Guid("ec8ce1b2-dba8-46f4-bd57-68ce7cf727d5"),
                            Address = "654 Southern Pkwy, Louisville, KY",
                            ContactInformation = "southerncomfortcafe@example.com",
                            Name = "Southern Comfort Cafe"
                        },
                        new
                        {
                            ID = new Guid("6c5a4129-046f-4c6e-b082-e078339b4286"),
                            Address = "987 Cherokee Rd, Louisville, KY",
                            ContactInformation = "cherokeeparkperks@example.com",
                            Name = "Cherokee Park Perks"
                        },
                        new
                        {
                            ID = new Guid("82d543d9-f70b-41f3-94b2-cf780ee229ca"),
                            Address = "135 Churchill Dr, Louisville, KY",
                            ContactInformation = "churchillgrinds@example.com",
                            Name = "Churchill Grinds"
                        },
                        new
                        {
                            ID = new Guid("ccd5de04-bdd7-42e9-a9f1-638c3efae7cd"),
                            Address = "246 East Market St, Louisville, KY",
                            ContactInformation = "nulujava@example.com",
                            Name = "NuLu Java"
                        });
                });

            modelBuilder.Entity("RoasterBuddy.Models.Order", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOrdered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoastLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ID = new Guid("3af4d7f6-bf1f-4da6-9d6f-097bc2a5c2b8"),
                            Amount = 10,
                            DateOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bluegrass Beans",
                            Price = 120.00m,
                            RoastLevel = "Light",
                            SourceName = "Fazenda Santa Ines, Minas Gerais, Brazil"
                        },
                        new
                        {
                            ID = new Guid("fe7600d6-745d-4ff0-be34-47ebf6090b02"),
                            Amount = 8,
                            DateOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "River City Roasts",
                            Price = 110.00m,
                            RoastLevel = "Medium",
                            SourceName = "Carmo Estate, Sul de Minas, Brazil"
                        },
                        new
                        {
                            ID = new Guid("898c64cc-0df1-42be-88a8-cb3b1e24adca"),
                            Amount = 6,
                            DateOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Derby Day Coffee",
                            Price = 140.00m,
                            RoastLevel = "Dark",
                            SourceName = "La Soledad, Acatenango, Guatemala"
                        },
                        new
                        {
                            ID = new Guid("5b48ce81-4e93-4888-a618-3360a906873f"),
                            Amount = 12,
                            DateOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bardstown Brews",
                            Price = 160.00m,
                            RoastLevel = "Medium",
                            SourceName = "Finca El Injerto, Huehuetenango, Guatemala"
                        },
                        new
                        {
                            ID = new Guid("c5124582-3b53-42e2-a199-db275c7fecfd"),
                            Amount = 9,
                            DateOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Southern Comfort Cafe",
                            Price = 180.00m,
                            RoastLevel = "Dark",
                            SourceName = "Hacienda La Esmeralda, Boquete, Panama"
                        },
                        new
                        {
                            ID = new Guid("baab65be-064b-46f5-b0ac-54e3b165edb7"),
                            Amount = 10,
                            DateOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cherokee Park Perks",
                            Price = 150.00m,
                            RoastLevel = "Medium",
                            SourceName = "Finca Deborah, Volcan, Panama"
                        },
                        new
                        {
                            ID = new Guid("91996708-d833-42a3-804a-90f9004332a2"),
                            Amount = 8,
                            DateOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Churchill Grinds",
                            Price = 120.00m,
                            RoastLevel = "Dark",
                            SourceName = "Hacienda El Roble, Santander, Colombia"
                        },
                        new
                        {
                            ID = new Guid("d6f03f16-048a-4ca8-952e-02fa81f9c2d8"),
                            Amount = 11,
                            DateOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "NuLu Java",
                            Price = 160.00m,
                            RoastLevel = "Medium",
                            SourceName = "Finca Los Nogales, Tolima, Colombia"
                        },
                        new
                        {
                            ID = new Guid("464b02e0-7082-40c6-9931-8078f3e35302"),
                            Amount = 9,
                            DateOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bluegrass Beans",
                            Price = 170.00m,
                            RoastLevel = "Light",
                            SourceName = "Hunkute Cooperative, Sidamo, Ethiopia"
                        },
                        new
                        {
                            ID = new Guid("afd0d4ad-c96d-4090-aee0-55aeeef90736"),
                            Amount = 7,
                            DateOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "River City Roasts",
                            Price = 150.00m,
                            RoastLevel = "Dark",
                            SourceName = "Guji Highland Farm, Guji, Ethiopia"
                        });
                });

            modelBuilder.Entity("RoasterBuddy.Models.Roast", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoastLevel")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Roasts");
                });

            modelBuilder.Entity("RoasterBuddy.Models.Source", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Farm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Sources");

                    b.HasData(
                        new
                        {
                            ID = new Guid("5d90ef3d-d504-4dcd-8c1f-d5699036c071"),
                            Cost = 2.40m,
                            Farm = "Fazenda Santa Ines, Minas Gerais",
                            Location = "Brazil"
                        },
                        new
                        {
                            ID = new Guid("1d3f4bfc-e3d1-414c-b202-100930c0dfc2"),
                            Cost = 2.75m,
                            Farm = "Carmo Estate, Sul de Minas",
                            Location = "Brazil"
                        },
                        new
                        {
                            ID = new Guid("7fc1027b-fe84-4b82-89fa-ec9023a60748"),
                            Cost = 4.67m,
                            Farm = "La Soledad, Acatenango",
                            Location = "Guatemala"
                        },
                        new
                        {
                            ID = new Guid("cac137ca-ea56-4f87-b33f-7fc72d9ab680"),
                            Cost = 2.67m,
                            Farm = "Finca El Injerto, Huehuetenango",
                            Location = "Guatemala"
                        },
                        new
                        {
                            ID = new Guid("6b221e39-41a7-45a6-908f-60dd71e77e50"),
                            Cost = 4.00m,
                            Farm = "Hacienda La Esmeralda, Boquete",
                            Location = "Panama"
                        },
                        new
                        {
                            ID = new Guid("60575eb9-a088-4ffc-9010-3c02a4ce87dd"),
                            Cost = 3.00m,
                            Farm = "Finca Deborah, Volcan",
                            Location = "Panama"
                        },
                        new
                        {
                            ID = new Guid("66a5636b-f794-4652-98c6-2cfdf32dbdfb"),
                            Cost = 3.00m,
                            Farm = "Hacienda El Roble, Santander",
                            Location = "Colombia"
                        },
                        new
                        {
                            ID = new Guid("8914d73b-c01d-45a5-9558-df60626a6436"),
                            Cost = 2.91m,
                            Farm = "Finca Los Nogales, Tolima",
                            Location = "Colombia"
                        },
                        new
                        {
                            ID = new Guid("25eed7af-23dd-42ce-ad63-38c075a22bd6"),
                            Cost = 3.78m,
                            Farm = "Hunkute Cooperative, Sidamo",
                            Location = "Ethiopia"
                        },
                        new
                        {
                            ID = new Guid("546b7556-57f0-46a6-b8a0-3dfcab4f8cdb"),
                            Cost = 4.29m,
                            Farm = "Guji Highland Farm, Guji",
                            Location = "Ethiopia"
                        });
                });

            modelBuilder.Entity("RoasterBuddy.Models.Order", b =>
                {
                    b.HasOne("RoasterBuddy.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("RoasterBuddy.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
